//****************************//
//*** LOCALHOST ***//
//****************************//

### GET ALL SERIES
GET http://localhost:8080/category

### GET SINGLE SERIE BY ID
GET http://localhost:8080/category/67a5e42f1e8bd7ff3749f376

### CREATE SERIE
POST http://localhost:8080/category/ HTTP/1.1
Content-Type: application/json

{
  "name": "Example 3",
  "description": "Great example",
  "createdAt": "2025-02-05T23:09:32.950Z",
  "updateAt": "2025-02-05T23:09:32.950Z"
}

### UPDATE SERIE BY ID
PUT http://localhost:8080/category/67a5e5b963d798e086784f78 HTTP/1.1
Content-Type: application/json

{
  "name": "Example 3 UPDATED",
  "description": "Great example",
  "createdAt": "2025-02-05T23:09:32.950Z",
  "updateAt": "2025-02-05T23:09:32.950Z"
}